title: Farid Shukurov
email: fshukurov19507@ada.edu.az
description: BsIT Student at ADA University | Class of 2029
baseurl: ""
url: "fshukurov09.github.io"

# Build settings
markdown: kramdown
theme: minima

# Social links
github_username: fshukurov09
codecademy_username: bubblegum1011

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
```